[[redirects]]
  from = "https://andreychevme.netlify.com/*"
  to = "https://andreychev.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://andreychev.ru/*"
  to = "https://andreychev.me/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "connect-src 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'none'"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
